import './globals.css'
import '@mantine/core/styles.css';

import { AppShell, AppShellHeader, AppShellMain, ColorSchemeScript } from '@mantine/core';
import type { Metadata } from 'next'

import Header from '@/components/Header';
import { interFont } from '@/fonts/inter';
import AppProviders from '@/providers/AppProviders';

export const metadata: Metadata = {
  title: 'SeaTheMoss',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body className={interFont.className}>
        <AppProviders>
          <AppShell header={{
            height: 60
          }}>
            <AppShellHeader>
              <Header />
            </AppShellHeader>
            <AppShellMain>
              {children}
            </AppShellMain>
          </AppShell>
        </AppProviders>
      </body>
    </html>
  )
}
